#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ $ARGV -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi
PATH = $1
IP = $2
USER = $3
SSH_KEY = $4

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH" "$USER@$IP:~/"
