#!/usr/bin/env bash
#Installation and configuration of Nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 775 /var/www/
echo Hello World! > /var/www/html/index.html
sudo service nginx restart
