#!/usr/bin/env bash
# A script that configures nginx to run at port 80
rm /etc/nginx/sites-enabled/default
cp -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
