#!/usr/bin/env bash
# Printing using while loop

i=1
while [ "$i" -le 10 ]
do 
    echo $i
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    (( i++ ))
done
