#!/usr/bin/env bash
# fix the container
pkill -f apache2
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80 /8080 /g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
